### ISSUE TITLE
Invalid browserify docs URLs in readme

### ISSUE THREAD

**Issue by jzaefferer** [HenrikJoreteg/moonboots#69]
Both URLs pointing at browserify docs are invalid, the anchors don't exist on the linked-to page anymore:

https://github.com/substack/node-browserify#bbundleopts-cb
https://github.com/substack/node-browserify#btransformtr

I'm trying to add a transform to browserfiy, but based on the documentation here and on browserfiy, can't figure out how to do that. Correct links would likely help a lot.

**Comment by jzaefferer** [comment]
For the record, I figured it out eventually:
```js
new Moonboots({
  moonboots: {
    browserify: {
      transform: 'envify'
    }
  }
})
```
As far as I can tell, the README is also wrong in stating that it passes options to browserify's `bundle()` method. The main module (what `require('browserify')` returns) accepts options as its second argument, that must be what's being passed through. The `bundle()` method only takes a callback argument.

**Comment by HenrikJoreteg** [comment]
Hi @jzaefferer, thanks for following up. Would you mind sending a PR to fix this?

**Comment by jzaefferer** [comment]
Sorry, can't help with addressing this. By now I'm not using this module anymore, but more importantly, I couldn't figure out what the URLs were supposed to point at.
